#spring.application.name=redis-demo

spring:
    data:
        redis:
            port: 6379
            host: 192.168.1.130
            password: root
            lettuce:
                pool:
                    max-active: 8
                    max-idle: 8
                    min-idle: 0
                    max-wait: 100ms

